/* Test try/catch block. */

function doStuff() {

    try {
        console.log("Hello World!");
    }
    catch(err) {
        console.log("Error: " + err);
    }

}

doStuff();
